import tempfile
import unittest
from contextlib import redirect_stderr, redirect_stdout
from io import StringIO
from pathlib import Path

from support import snapshot, tool


def section(report, title):
    return report.split("\n## %s\n" % title, 1)[1].split("\n## ", 1)[0]


class ChangesFile(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.report = tool.render_changes(snapshot("v1", "9.9.9"), snapshot("v2", "9.9.10"))

    def test_says_it_is_generated_and_names_both_versions(self):
        head = self.report.split("\n## ", 1)[0]
        self.assertIn("Generated by", head)
        self.assertIn("effect@9.9.9", head)
        self.assertIn("effect@9.9.10", head)

    def test_carries_no_verified_stamp(self):
        self.assertNotIn("verified:", self.report)
        self.assertIsNone(tool.STAMP_RE.match(self.report.split("\n", 1)[0]))

    def test_unstable_removals_and_changes_are_grouped_by_module(self):
        unstable = section(self.report, "Unstable and experimental exports")
        self.assertIn("### `effect/http/Router`", unstable)
        self.assertIn("module was removed", unstable.split("### `effect/http/Router`")[1])
        self.assertIn("### `effect/Effect`", unstable)
        self.assertIn("`Tagged` (type) [stable]: changed, tier unstable -> stable",
                      unstable.split("### `effect/Effect`")[1])

    def test_stable_breaks_are_in_their_own_section(self):
        stable = section(self.report, "Stable exports removed or changed")
        self.assertIn("`map` [stable]: removed (const)", stable)
        self.assertIn("`succeed` [stable]: changed, declaration changed", stable)
        self.assertNotIn("`map`", section(self.report, "Unstable and experimental exports"))
        self.assertNotIn("http/Router", stable)

    def test_additions_are_only_counted(self):
        added = section(self.report, "Added")
        self.assertIn("2 exports and 1 module added", added)
        self.assertNotIn("brandNew", self.report)
        self.assertNotIn("Fresh", self.report)

    def test_no_changes_still_names_versions_and_says_none(self):
        s = snapshot("v1", "9.9.9")
        report = tool.render_changes(s, s)
        self.assertEqual(report.count("None."), 2)
        self.assertIn("0 exports and 0 modules added", report)

    def test_is_deterministic(self):
        self.assertEqual(self.report, tool.render_changes(snapshot("v1", "9.9.9"), snapshot("v2", "9.9.10")))

    def test_command_prints_the_rendered_file(self):
        with tempfile.TemporaryDirectory() as d:
            paths = []
            for tree, ver in (("v1", "9.9.9"), ("v2", "9.9.10")):
                p = Path(d) / (ver + ".json")
                p.write_text(tool.dump_snapshot(snapshot(tree, ver)))
                paths.append(str(p))
            out = StringIO()
            with redirect_stdout(out):
                rc = tool.main(["changes"] + paths)
        self.assertEqual(rc, 0)
        self.assertIn("effect 9.9.9 -> 9.9.10", out.getvalue())
        self.assertIn("## Stable exports removed or changed", out.getvalue())

    def test_unreadable_snapshot_fails_with_1(self):
        with redirect_stdout(StringIO()), redirect_stderr(StringIO()):
            self.assertEqual(tool.main(["changes", "/no/such/a.json", "/no/such/b.json"]), 1)


if __name__ == "__main__":
    unittest.main()
